ARG FYNE_CROSS_IMAGES_VERSION=dev
ARG FYNE_CROSS_REPOSITORY=docker.io/fyneio/fyne-cross-images

# fyne-cross image for linux
FROM ${FYNE_CROSS_REPOSITORY}:${FYNE_CROSS_IMAGES_VERSION}-darwin

COPY sdk /sdk
